/* === ANCHOR: SECTIONS TO ADD BY DAY === */

// * === TODO === */

// == Show: DAY 3 - Reset Score
// router.post('/:exercise_id/:question_id', (res, req) => {
    
    // Grab id from cookie generated by authController
        // userId = req.session.currentUser.id
    // Delete data in UserAnswer    
        // UserAnswer.deleteMany( {userId} )

// });

// Day 4 for security
// npm i: morgan, rateLimit, helmet, mongoSanitize, hpp
    // server.js: require
    // server.js MIDDLEWARES: app.use()


// TO DO - Add a congrats page!!!


// Exercise Feedback: Delay
// setTimeout(() => {
//     console.log('redirect after 1 seconds')
// }, 1000);



/* === NOTE: Base packages === */

// == npm i
// express
// mongoose
// method-override
// nodemon
// dotenv

// == base implementation
// methodOverride: CRUD - So we can use UPDATE as PUT
// urlEncoded: CRUD - So we can use CREATE and UPDATE with req.body

