/* === External Modules: express === */
const express = require('express');

/* === System Variables: route === */
const router = express.Router();

/* === Routes | base url: /exercise === */

// Show
router.get('/:language/:exercise_id/:question_id', (req, res) => {
    language = req.params.language;
    exercise_id = req.params.exercise_id;
    question_id = req.params.question_id;

    res.send({
        msg: `Exercise page`, 
        language: language,
        exercise: exercise_id, 
        question: question_id,
    });

    // res.render('/exercises)

});

// Show: DAY 2 - Correct Answer

// Show: DAY 3 - Skip to next exercise

// Show: DAY 3 - Reset score


/* === Exports: route === */
module.exports = router;









// * === TODO === */

// == DAY 2 - Correct Answer
// Current approach: Same as Update Product
// New approach: Ask how to show answer without reload

// router.get('/:language/:exercise_id/:question_id/answer', (req, res) => { res.render('/../answer')});

// Show: DAY 2 - Correct Answer


// == Show: DAY 3 - Reset Score
// router.post('/:exercise_id/:question_id', (res, req) => {
    
    // Grab id from cookie generated by authController
        // userId = req.session.currentUser.id
    // Delete data in UserAnswer    
        // UserAnswer.deleteMany( {userId} )

// });